# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action_map',
            options={},
        ),
        migrations.AddField(
            model_name='action_map',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action_map',
            name='sub_flow',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='test_result',
            name='sub_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM.Action_Map', to_field='sub_flow'),
        ),
    ]
