# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_auto_20160408_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action_map',
            options={'ordering': ['instrument_model']},
        ),
        migrations.AlterField(
            model_name='test_result',
            name='sub_flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM.Action_Map'),
        ),
    ]
