# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0004_auto_20160411_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_detail',
            name='device',
            field=models.CharField(default='xx', max_length=30),
            preserve_default=False,
        ),
    ]
