# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0005_log_detail_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='test_log',
            name='device',
        ),
        migrations.AlterField(
            model_name='log_detail',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATM.Device'),
        ),
    ]
