# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 03:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0006_auto_20160413_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log_detail',
            options={'ordering': ['log_name']},
        ),
    ]
