# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 10:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0008_auto_20160616_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_detail',
            name='device',
        ),
    ]
