# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0009_remove_log_detail_device'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log_Detail',
            new_name='Result_Detail',
        ),
    ]
