# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0010_auto_20160620_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='action_map',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ATM.Device'),
            preserve_default=False,
        ),
    ]
