# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STReport', '0002_auto_20160408_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='st_log',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='st_log',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
