# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STReport', '0003_auto_20160408_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='st_log',
            name='tape',
        ),
        migrations.AddField(
            model_name='st_log',
            name='st_tape',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='st_log',
            name='tcct_tape',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
