# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STReport', '0004_auto_20160412_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_log',
            name='workstation_model',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='workstation_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
