# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STReport', '0006_auto_20160524_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='st_log',
            old_name='remarks',
            new_name='remarks_mem',
        ),
        migrations.AddField(
            model_name='st_log',
            name='remarks_tet',
            field=models.TextField(blank=True),
        ),
    ]
