# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import new_api.files


class Migration(migrations.Migration):

    dependencies = [
        ('STReport', '0007_auto_20160606_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_log',
            name='begin_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='data_csv',
            field=models.FileField(max_length=91, storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/var/www/DFT/files/streport'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='data_log',
            field=models.FileField(storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/var/www/DFT/files/streport'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='spike_csv',
            field=models.FileField(blank=True, max_length=93, storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/var/www/DFT/files/streport'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='time_csv',
            field=models.FileField(blank=True, max_length=92, storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/var/www/DFT/files/streport'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='st_log_attach',
            name='attachment',
            field=models.FileField(max_length=94, storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/var/www/DFT/files/streport'), upload_to=''),
        ),
    ]
