# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-07-23 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import new_api.files


class Migration(migrations.Migration):

    dependencies = [
        ('STReport', '0008_auto_20160829_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_log',
            name='data_csv',
            field=models.FileField(max_length=91, storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/localworkspaces/larissalv/SM/DFT/./files/streport'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='data_log',
            field=models.FileField(storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/localworkspaces/larissalv/SM/DFT/./files/streport'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='spike_csv',
            field=models.FileField(blank=True, max_length=93, storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/localworkspaces/larissalv/SM/DFT/./files/streport'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='st_tape',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='tcct_tape',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='time_csv',
            field=models.FileField(blank=True, max_length=92, storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/localworkspaces/larissalv/SM/DFT/./files/streport'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='st_log',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='st_log_attach',
            name='attachment',
            field=models.FileField(max_length=94, storage=new_api.files.OverwriteStorage(base_url='/files/streport', location='/localworkspaces/larissalv/SM/DFT/./files/streport'), upload_to=''),
        ),
    ]
